title: 'My randomness '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5494092
  brandStrength: 0.1055742385797203
  lightness: 0.4312567
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  rhythmicContrast: 0.689044
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Lorenzo Morales Jr
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7803437
layout_spectrum: 0.4709989
